# Análisis de datos con Numpy

Importamos la libería

In [22]:
import numpy as np

## Variables

In [23]:
productos = 10
tiendas = 5
dias = 7

## Funciones

In [24]:
def generar_datos_ventas(productos, tiendas, dias):
    # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    return np.random.randint(0, 101, (productos, tiendas, dias))

In [25]:
def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

In [26]:
def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

In [27]:
def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

In [28]:
def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))

In [41]:
def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

In [40]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas


## Generar los datos de ventas

In [29]:
datos = generar_datos_ventas(productos, tiendas, dias)
datos


array([[[ 20,  40,  87,  16,  24,  99,  85],
        [ 38,  88,  69,  42,  20,  42,  37],
        [ 34,  77,  93,  92,  70,  18,   1],
        [ 54,  53,  28,   3,  22,  10,   2],
        [ 96,  84,  43,  82,  45,  56,  63]],

       [[ 94,  19,  48,  90,  57,   9,  24],
        [ 29,  39,  82,  73,  95,  89,  40],
        [ 97,  32,   6,  15,  86,  60,  23],
        [ 63,  88,  27,  35,  77,  89,  83],
        [ 36,  96,  20,  55,   4,  66,  81]],

       [[ 95,  88,  93,  90,   4,  57,  27],
        [ 20,  85,  30,  53,  20,   0,  19],
        [ 57,  91,  57,  37,  21,  71,  14],
        [ 56,  46,   0,  99,  16,   9,  31],
        [ 58,  87,  65,  68,  82,   4,  19]],

       [[ 26,  19,  52,  59,  95,  36,  64],
        [  1,  54,  56,   6,  40,  28,  15],
        [ 27,  89,   2,  65,  14,  52,  34],
        [ 75,  52,  68,  57,  75,  68,  28],
        [ 58,  90,  53,  72,  74,  66,  65]],

       [[  6,  57,  33,  55,  61,  87,  79],
        [ 12,  11,  64,  72,  64,  94,  45],
  

## Cáculo de totales y promedios

In [30]:
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_producto

array([1733, 1927, 1669, 1735, 1722, 1495, 1578, 1617, 1845, 1824])

In [31]:
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
totales_por_tienda

array([3500, 3276, 3329, 3501, 3539])

In [32]:
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_producto

array([49.51428571, 55.05714286, 47.68571429, 49.57142857, 49.2       ,
       42.71428571, 45.08571429, 46.2       , 52.71428571, 52.11428571])

In [33]:
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)
promedio_por_tienda

array([50.        , 46.8       , 47.55714286, 50.01428571, 50.55714286])

## Tiendas y productos con mayor y menor número de ventas

In [45]:
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)


5


## Resultados

In [46]:
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

Total de ventas por producto a lo largo de la semana: [1733 1927 1669 1735 1722 1495 1578 1617 1845 1824]
Total de ventas por tienda a lo largo de la semana: [3500 3276 3329 3501 3539]
Promedio de ventas por producto por día: [49.51428571 55.05714286 47.68571429 49.57142857 49.2        42.71428571
 45.08571429 46.2        52.71428571 52.11428571]
Promedio de ventas por tienda por día: [50.         46.8        47.55714286 50.01428571 50.55714286]
Producto con mayor ventas: Producto 1
Producto con menor ventas: Producto 5
Tienda con mayor ventas: Tienda 4
Tienda con menor ventas: Tienda 1
